import React from 'react';
import { TabType } from '../types';

interface BottomNavProps {
  activeTab: TabType;
  setActiveTab: (tab: TabType) => void;
}

export const BottomNav: React.FC<BottomNavProps> = ({ activeTab, setActiveTab }) => {
  // NOTE: these tabs previously used `iconUrl` pointing at ephemeral
  // https://lh3.googleusercontent.com/aida-public/... images generated by
  // aistudio.google.com. Those links are session-scoped and eventually stop
  // resolving, which is why every bottom-nav icon rendered broken. Each tab
  // already carried a matching Material Symbols name (`icon`) that was never
  // actually rendered — we now use that instead of the broken remote image,
  // so no asset or feature is removed, the icon just loads reliably.
  const tabs: { id: TabType; label: string; icon: string }[] = [
    { id: 'home', label: 'خانه', icon: 'home' },
    { id: 'products', label: 'محصولات', icon: 'grid_view' },
    { id: 'orders', label: 'سفارشات', icon: 'receipt_long' },
    { id: 'visitor', label: 'ارتباط با ویزیتور', icon: 'support_agent' },
    { id: 'profile', label: 'حساب کاربری', icon: 'person' },
  ];

  return (
    <div className="fixed bottom-3 left-1/2 -translate-x-1/2 w-[calc(100%-24px)] max-w-[424px] z-40 p-[2px] rounded-2xl bg-gradient-to-r from-[#10b981] via-[#34d399] to-[#059669] shadow-[0_0_20px_rgba(16,185,129,0.35),0_10px_25px_-5px_rgba(0,108,74,0.3)]">
      <nav className="w-full bg-[#f4fbf7]/95 backdrop-blur-2xl rounded-[14px] h-18 px-2 flex justify-around items-center flex-row">
        {tabs.map((tab) => {
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex flex-col items-center justify-center h-full px-2.5 active:scale-95 transition-all relative ${
                isActive
                  ? 'text-[#006c4a] opacity-100 font-extrabold'
                  : 'text-[#525b56] opacity-75 hover:opacity-100 font-bold'
              }`}
            >
              {isActive && (
                <span className="absolute top-1.5 inset-x-3 h-1 bg-[#006c4a] rounded-full shadow-[0_0_8px_rgba(0,108,74,0.6)]" />
              )}
              <div className="relative w-6 h-6 flex items-center justify-center mb-1 mt-1">
                <span
                  className={`material-symbols-outlined text-[24px] leading-none transition-transform ${
                    isActive ? 'scale-110' : ''
                  }`}
                  style={isActive ? { fontVariationSettings: "'FILL' 1" } : undefined}
                >
                  {tab.icon}
                </span>
              </div>
              <span className="font-['Vazirmatn'] text-[11px] leading-none">
                {tab.label}
              </span>
            </button>
          );
        })}
      </nav>
    </div>
  );
};
