import { Brand, Customer, Order, Product } from './types';

export const INITIAL_BRANDS: Brand[] = [
  { id: 'b1', name: 'کدکس', imageUrl: '/brands/kodex.png', englishName: 'Kodex', logoColor: 'from-purple-600 to-indigo-700', active: true },
  { id: 'b2', name: 'آمبرلا', imageUrl: '/brands/umbrella.png', englishName: 'Umbrella', logoColor: 'from-amber-500 to-orange-600', active: true },
  { id: 'b3', name: 'پیکسلی', imageUrl: '/brands/pixel.png', englishName: 'Pixel', logoColor: 'from-blue-600 to-cyan-600', active: true },
  { id: 'b4', name: 'میس‌ویک', imageUrl: '/brands/misswake.png', englishName: 'Misswake', logoColor: 'from-emerald-600 to-teal-700', active: true },
  { id: 'b5', name: 'کاپوت', imageUrl: '/brands/kaput.png', englishName: 'Kaput', logoColor: 'from-rose-600 to-red-700', active: true },
  { id: 'b6', name: 'دافی', imageUrl: '/brands/dafi.png', englishName: 'Dafi', logoColor: 'from-sky-500 to-blue-600', active: true },
  { id: 'b7', name: 'کامان', imageUrl: '/brands/comeon.png', englishName: 'Comeon', logoColor: 'from-emerald-500 to-green-700', active: true },
  { id: 'b8', name: 'نینو', imageUrl: '/brands/nino.png', englishName: 'Nino', logoColor: 'from-cyan-500 to-blue-600', active: true },
  { id: 'b9', name: 'زنون', imageUrl: '/brands/zenon.png', englishName: 'Zenon', logoColor: 'from-slate-700 to-slate-900', active: true },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    code: '۴۰۸۹۲',
    storeName: 'داروخانه دکتر رضایی',
    ownerName: 'دکتر علی رضایی',
    phone: '۰۹۱۲۳۴۵۶۷۸۹',
    businessType: 'داروخانه',
    address: 'تهران، خیابان ولیعصر، بالاتر از میدان ونک، پلاک ۲۴۵',
    marketerName: 'مهندس احمدی',
    marketerPhone: '۰۹۱۹۸۷۶۵۴۳۲',
    active: true,
  },
  {
    id: 'c2',
    code: '۵۰۱۲۳',
    storeName: 'فروشگاه آرایشی و بهداشتی صدف',
    ownerName: 'سارا محمدی',
    phone: '۰۹۱۲۹۸۷۶۵۴۳',
    businessType: 'فروشگاه آرایشی و بهداشتی',
    address: 'تهران، میدان تجریش، پاساژ قائم، طبقه اول، پلاک ۴۲',
    marketerName: 'خانم قاسمی',
    marketerPhone: '۰۹۳۵۱۱۱۲۲۳۳',
    active: true,
  },
  {
    id: 'c3',
    code: '۶۰۴۵۶',
    storeName: 'سوپرمارکت بزرگ کوروش',
    ownerName: 'رضا حسینی',
    phone: '۰۹۱۲۵۵۵۴۴۳۳',
    businessType: 'سوپرمارکت',
    address: 'تهران، سعادت‌آباد، بلوار پاکنژاد، کوچه بهار، پلاک ۱۰',
    marketerName: 'مهندس احمدی',
    marketerPhone: '۰۹۱۹۸۷۶۵۴۳۲',
    active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    code: 'KDX-101',
    imageUrl: '/products/kodex-double-delay.jpg',
    name: 'کاندوم کدکس مدل Double Delay بسته ۱۲ عددی',
    brand: 'کدکس',
    category: 'بهداشت زناشویی',
    imageColor: 'bg-purple-100 text-purple-700',
    iconType: 'shield',
    cartonQuantity: 48, // 48 بسته در هر کارتن
    price: 2880000, // قیمت کارتن (تومان)
    unitPrice: 60000,
    inStock: true,
    stockCount: 120,
    specialOffer: true,
    discountPercentage: 10,
    isNew: false,
    description: 'دارای ماده تاخیری مضاعف، ساخته شده از لاتکس طبیعی، ساختار مرغوب و مقاوم جهت بهداشت خانواده.',
    active: true,
  },
  {
    id: 'p2',
    code: 'KDX-102',
    imageUrl: '/products/kodex-master-3in1.jpg',
    name: 'کاندوم کدکس مدل Master 3 in 1 بسته ۱۲ عددی',
    brand: 'کدکس',
    category: 'بهداشت زناشویی',
    imageColor: 'bg-indigo-100 text-indigo-700',
    iconType: 'sparkles',
    cartonQuantity: 48,
    price: 3120000,
    unitPrice: 65000,
    inStock: true,
    stockCount: 85,
    specialOffer: false,
    isNew: true,
    description: 'دارای ماده تاخیری بنزوکائین جهت تاخیر در انزال، دارای حلقه و شیارهای برجسته جهت تحریک بیشتر، رایحه مطبوع میوه‌ای و لاتکس ۱۰۰٪ طبیعی.',
    active: true,
  },
  {
    id: 'p3',
    code: 'UMB-201',
    imageUrl: '/products/umbrella-oil-plus.jpg',
    name: 'کرم مرطوب‌کننده و آبرسان آمبرلا مدل Oil Plus ۷۵ml',
    brand: 'آمبرلا',
    category: 'مراقبت پوست',
    imageColor: 'bg-amber-100 text-amber-700',
    iconType: 'droplet',
    cartonQuantity: 24,
    price: 1800000,
    unitPrice: 75000,
    inStock: true,
    stockCount: 200,
    specialOffer: true,
    discountPercentage: 15,
    isNew: true,
    description: 'حاوی روغن آووکادو، شی‌باتر، روغن بادام شیرین و روغن زیتون، آبرسانی عمیق و تغذیه پوست دست و صورت با جذب بسیار سریع.',
    active: true,
  },
  {
    id: 'p4',
    code: 'UMB-202',
    imageUrl: '/products/umbrella-face-wash-oily.jpg',
    name: 'ژل شستشوی صورت آمبرلا مخصوص پوست‌های چرب ۳۰۰ml',
    brand: 'آمبرلا',
    category: 'مراقبت پوست',
    imageColor: 'bg-orange-100 text-orange-700',
    iconType: 'sun',
    cartonQuantity: 12,
    price: 1560000,
    unitPrice: 130000,
    inStock: true,
    stockCount: 50,
    specialOffer: false,
    isNew: false,
    description: 'تنظیم‌کننده چربی پوست، پاک‌کننده عمقی منافذ، حاوی سالیسیلیک اسید و عصاره بابونه.',
    active: true,
  },
  {
    id: 'p5',
    code: 'PXL-301',
    imageUrl: '/products/pixel-sunscreen-spf50-matte.jpg',
    name: 'کرم ضدآفتاب رنگی پیکسلی SPF 50 سری مات',
    brand: 'پیکسلی',
    category: 'مراقبت پوست',
    imageColor: 'bg-blue-100 text-blue-700',
    iconType: 'sun',
    cartonQuantity: 24,
    price: 3840000,
    unitPrice: 160000,
    inStock: true,
    stockCount: 40,
    specialOffer: true,
    discountPercentage: 12,
    isNew: false,
    description: 'محافظت کامل در برابر UVA و UVB، پوشش‌دهی طبیعی، مقاوم در برابر تعریق و بدون چربی اضافی.',
    active: true,
  },
  {
    id: 'p6',
    code: 'DFI-401',
    imageUrl: '/products/dafi-5in1-70ct.jpg',
    name: 'دستمال مرطوب پاک‌کننده آرایش دافی مدل 5in1 بسته ۷۰ عددی',
    brand: 'دافی',
    category: 'بهداشتی و سلولزی',
    imageColor: 'bg-sky-100 text-sky-700',
    iconType: 'layers',
    cartonQuantity: 36,
    price: 2160000,
    unitPrice: 60000,
    inStock: true,
    stockCount: 150,
    specialOffer: false,
    isNew: false,
    description: 'پاک‌کننده ملایم آرایش ضدآب، بدون الکل و پارابن، حاوی ویتامین E و عصاره بابونه.',
    active: true,
  },
  {
    id: 'p7',
    code: 'DFI-402',
    imageUrl: '/products/dafi-sensitive-baby-wipes.jpg',
    name: 'دستمال مرطوب کودک دافی مدل Sensitive بسته ۱۰۰ عددی',
    brand: 'دافی',
    category: 'بهداشتی و سلولزی',
    imageColor: 'bg-teal-100 text-teal-700',
    iconType: 'heart',
    cartonQuantity: 24,
    price: 1920000,
    unitPrice: 80000,
    inStock: true,
    stockCount: 90,
    specialOffer: true,
    discountPercentage: 8,
    isNew: false,
    description: 'ویژه پوست حساس نوزاد، فاقد عطر و مواد شیمیایی مضر، دارای لوسیون نرم‌کننده.',
    active: true,
  },
  {
    id: 'p8',
    code: 'CMN-501',
    imageUrl: '/products/comeon-waterbomb-200ml.jpg',
    name: 'واتر بمب کامان حاوی هیالورونیک اسید ۲۰۰ml',
    brand: 'کامان',
    category: 'مراقبت پوست',
    imageColor: 'bg-emerald-100 text-emerald-700',
    iconType: 'droplet',
    cartonQuantity: 12,
    price: 2280000,
    unitPrice: 190000,
    inStock: true,
    stockCount: 65,
    specialOffer: false,
    isNew: true,
    description: 'آبرسان فوق‌العاده قوی بمب آبرسان، ماندگاری ۷۲ ساعته رطوبت، مناسب انواع پوست.',
    active: true,
  },
  {
    id: 'p9',
    code: 'CMN-502',
    imageUrl: '/products/comeon-mens-shampoo.jpg',
    name: 'شامپو سر و بدن آقایان کامان ۵۰۰ml',
    brand: 'کامان',
    category: 'مراقبت مو و بدن',
    imageColor: 'bg-green-100 text-green-800',
    iconType: 'zap',
    cartonQuantity: 12,
    price: 1680000,
    unitPrice: 140000,
    inStock: false, // Out of stock example
    stockCount: 0,
    specialOffer: false,
    isNew: false,
    description: 'پاک‌کننده عمیق با حس خنکی نعناع و کافئین، خنثی‌کننده بوی بد تعریق.',
    active: true,
  },
  {
    id: 'p10',
    code: 'KPT-101',
    imageUrl: '/products/kaput-micro-thin.jpg',
    name: 'کاندوم کاپوت مدل Micro Thin بسته ۱۲ عددی',
    brand: 'کاپوت',
    category: 'بهداشت زناشویی',
    imageColor: 'bg-rose-100 text-rose-700',
    iconType: 'shield',
    cartonQuantity: 48,
    price: 2880000,
    unitPrice: 60000,
    inStock: true,
    stockCount: 100,
    specialOffer: true,
    discountPercentage: 15,
    isNew: false,
    description: 'طراحی فوق‌العاده نازک جهت احساس طبیعی، ساخته شده از لاتکس طبیعی مرغوب با لوبریکانت روان‌کننده و رایحه مطبوع.',
    active: true,
  },
  {
    id: 'p11',
    code: 'NIN-201',
    imageUrl: '/products/nino-sensitive-baby-wipes.jpg',
    name: 'دستمال مرطوب کودک نینو مدل Sensitive بسته ۶۴ عددی',
    brand: 'نینو',
    category: 'بهداشتی و سلولزی',
    imageColor: 'bg-cyan-100 text-cyan-700',
    iconType: 'heart',
    cartonQuantity: 24,
    price: 1920000,
    unitPrice: 80000,
    inStock: true,
    stockCount: 75,
    specialOffer: false,
    isNew: false,
    description: 'مخصوص پوست حساس نوزاد و کودک، فاقد الکل و پارابن و مواد صابونی، حاوی عصاره بابونه و کالندولا.',
    active: true,
  },
  {
    id: 'p12',
    code: 'ZNN-301',
    imageUrl: '/products/zenon-legend-deodorant.jpg',
    name: 'اسپری دئودورانت مردانه زنون مدل Legend حجم ۱۵۰ml',
    brand: 'زنون',
    category: 'مراقبت مو و بدن',
    imageColor: 'bg-slate-200 text-slate-800',
    iconType: 'zap',
    cartonQuantity: 24,
    price: 2160000,
    unitPrice: 90000,
    inStock: true,
    stockCount: 110,
    specialOffer: false,
    isNew: false,
    description: 'اسپری خوشبوکننده و ضدتعریق بدن آقایان با ماندگاری ۴۸ ساعته، رایحه خنک و جذاب بدون ایجاد لک روی لباس.',
    active: true,
  },
  {
    id: 'p13',
    code: 'MSW-401',
    imageUrl: '/products/misswake-total8.jpg',
    name: 'خمیر دندان میس‌ویک مدل Total 8 حجم ۷۵ml',
    brand: 'میس‌ویک',
    category: 'بهداشت دهان و دندان',
    imageColor: 'bg-emerald-100 text-emerald-800',
    iconType: 'smile',
    cartonQuantity: 36,
    price: 2520000,
    unitPrice: 70000,
    inStock: true,
    stockCount: 130,
    specialOffer: true,
    discountPercentage: 10,
    isNew: true,
    description: 'محافظت کامل ۸ کاره از دندان‌ها و لثه، حاوی آنزیم طبیعی محافظ مینای دندان، ضدپلاک و خوشبوکننده دهان.',
    active: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'SS-۱۴۰۳۰۵۲۱',
    customerId: 'c1',
    storeName: 'داروخانه دکتر رضایی',
    orderDate: '۱۴۰۳/۰۵/۲۰ - ۱۰:۱۵',
    items: [
      {
        id: 'oi-1',
        orderId: 'ord-101',
        productId: 'p1',
        productName: 'کاندوم کدکس مدل Double Delay بسته ۱۲ عددی',
        brand: 'کدکس',
        quantity: 2, // 2 cartons
        cartonQuantity: 48,
        unitPrice: 2880000,
        totalPrice: 5760000,
      },
      {
        id: 'oi-2',
        orderId: 'ord-101',
        productId: 'p3',
        productName: 'کرم مرطوب‌کننده و آبرسان آمبرلا مدل Oil Plus ۷۵ml',
        brand: 'آمبرلا',
        quantity: 1,
        cartonQuantity: 24,
        unitPrice: 1800000,
        totalPrice: 1800000,
      },
    ],
    initialAmount: 7560000,
    discount: 378000, // 5% bulk discount
    finalAmount: 7182000,
    status: 'ارسال شده',
    customerNote: 'لطفاً تحویل نوبت صبح صورت گیرد.',
    adminNote: 'توسط انبار مرکز فاکتور و ارسال شد.',
  },
  {
    id: 'ord-102',
    orderNumber: 'SS-۱۴۰۳۰۵۲۴',
    customerId: 'c1',
    storeName: 'داروخانه دکتر رضایی',
    orderDate: '۱۴۰۳/۰۵/۲۴ - ۱۶:۴۰',
    items: [
      {
        id: 'oi-3',
        orderId: 'ord-102',
        productId: 'p8',
        productName: 'واتر بمب کامان حاوی هیالورونیک اسید ۲۰۰ml',
        brand: 'کامان',
        quantity: 3,
        cartonQuantity: 12,
        unitPrice: 2280000,
        totalPrice: 6840000,
      },
    ],
    initialAmount: 6840000,
    discount: 342000,
    finalAmount: 6498000,
    status: 'در حال بررسی',
    customerNote: 'با تشکر از همکاری شما.',
  },
  {
    id: 'ord-103',
    orderNumber: 'SS-۱۴۰۳۰۵۲۵',
    customerId: 'c1',
    storeName: 'داروخانه دکتر رضایی',
    orderDate: '۱۴۰۳/۰۵/۲۵ - ۰۹:۰۰',
    items: [
      {
        id: 'oi-4',
        orderId: 'ord-103',
        productId: 'p5',
        productName: 'کرم ضدآفتاب رنگی پیکسلی SPF 50 سری مات',
        brand: 'پیکسلی',
        quantity: 1,
        cartonQuantity: 24,
        unitPrice: 3840000,
        totalPrice: 3840000,
      },
      {
        id: 'oi-5',
        orderId: 'ord-103',
        productId: 'p6',
        productName: 'دستمال مرطوب پاک‌کننده آرایش دافی مدل 5in1 بسته ۷۰ عددی',
        brand: 'دافی',
        quantity: 2,
        cartonQuantity: 36,
        unitPrice: 2160000,
        totalPrice: 4320000,
      },
    ],
    initialAmount: 8160000,
    discount: 408000,
    finalAmount: 7752000,
    status: 'ثبت شده',
  },
];

